<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Cedar.Core</PackageId>
    <Version>0.1.0</Version>
    <Authors>TheFellow</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/TheFellow/cedar-dotnet</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Internal\Parser\**\*.cs" />
    <Compile Remove="Internal\Rust\**\*.cs" />
    <Compile Remove="Policy.cs" />
    <Compile Remove="PolicySet.cs" />
    <Compile Remove="PolicyList.cs" />
    <Compile Remove="Annotations.cs" />
    <Compile Remove="IPolicyIterator.cs" />
    <Compile Remove="Encoder.cs" />
    <Compile Remove="Decoder.cs" />
    <Compile Remove="Internal\Json\NodeJsonModel.cs" />
    <Compile Remove="Internal\Json\ScopeJsonModel.cs" />
    <Compile Remove="Internal\Json\PolicyJsonModel.cs" />
    <Compile Remove="Internal\Json\PolicyJsonMarshal.cs" />
    <Compile Remove="Internal\Json\PolicyJsonUnmarshal.cs" />
    <Compile Remove="Internal\Json\PolicySetJsonModel.cs" />
    <Compile Remove="Internal\Json\PolicyJsonSerializerOptions.cs" />
    <Compile Remove="Internal\Eval\**\*.cs" />
    <Compile Remove="Internal\Extensions\**\*.cs" />
    <Compile Remove="Authorization.cs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cedar.Tests" />
    <InternalsVisibleTo Include="Cedar.Ast" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cedar.Types\Cedar.Types.csproj" />
  </ItemGroup>
</Project>
