<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Cedar.Experimental</PackageId>
    <Version>0.2.0</Version>
    <Authors>TheFellow</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/TheFellow/cedar-dotnet</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cedar.Experimental.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cedar.Core\Cedar.Core.csproj" />
    <ProjectReference Include="..\Cedar.Ast\Cedar.Ast.csproj" />
  </ItemGroup>
</Project>
